# action.yml
# Defines the action, along with its input and output parameters
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  OUTPUT_TIME: # id of output
    description: "The time we greeted returned as date from the container"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
